engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
      enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
      ignore_warnings: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode"
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- config/**/*
